[build]
  command = "python manage.py collectstatic --no-input && pip install -r requirements.txt"
  publish = "staticfiles"
  functions = "netlify/functions"

[dev]
  command = "python manage.py runserver"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "emojitracker.settings.production"