# Generated by Django 4.2.16 on 2024-09-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_emoji',
            field=models.CharField(default='😊', max_length=2),
        ),
    ]
