name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests
          run: |
            python manage.py test
    
    deploy:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        
        steps:
            - uses: actions/checkout@v4
      
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v3.0
              with:
                publish-dir: './dist'
                production-branch: main
                deploy-message: "Deploy from GitHub Actions"
                enable-pull-request-comment: false
                enable-commit-comment: true
                overwrites-pull-request-comment: true
              env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1